name: CML

on:
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v1
      - name: Install DVC
        run: |
          pip install dvc
      - name: Check if DVC is initialized
        id: check_dvc_init
        run: |
          if [ ! -d ".dvc" ]; then
            echo "DVC not initialized"
            echo "::set-output name=dvc_initialized::false"
          else
            echo "DVC is already initialized"
            echo "::set-output name=dvc_initialized::true"
          fi
        continue-on-error: true
      - name: Set up DVC and myremote
        run: |
          if [ -z "${{ secrets.BUCKET_NAME }}" ]; then
            echo "Error: BUCKET_NAME environment variable not set."
            exit 1
          fi
          dvc remote add -f -d myremote gs://${{ secrets.BUCKET_NAME }}/
          dvc remote modify --local myremote credentialpath './credentials.json'

  train_and_report:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up environment
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "$GOOGLE_APPLICATION_CREDENTIALS" | base64 --decode | jq > credentials.json
          pip install -r requirements.txt
      - name: Pull data from GCS
        if: needs.setup.outputs.dvc_initialized == 'true'
        run: |
          dvc pull
      - name: Train model
        if: needs.setup.outputs.dvc_initialized == 'true'
        run: |
          python src/train.py --cml_run
      - name: Update report and comment
        if: needs.setup.outputs.dvc_initialized == 'true'
        run: |
          cat metrics.txt >> report.md
          cml comment create report.md
          rm credentials.json
